package feudal_web.exception;

import org.springframework.http.HttpStatus;

public class CustomValidationFailedException extends RuntimeException {

	/**
	 * Required by RuntimeException, value generated by Eclipse
	 */
	private static final long serialVersionUID = -1439958071174318831L;
	
	private final HttpStatus statusCode;
	
	public CustomValidationFailedException(String message, HttpStatus statusCode) {
		super(message);
		this.statusCode = statusCode;
	}

	public HttpStatus getStatusCode() {
		return statusCode;
	}

}
